### ISSUE TITLE
Doesn't boot on OnePlus 8 Pro

### ISSUE THREAD

**Issue by tbalden** [OnePlusOSS/android_kernel_oneplus_sm8250#1]
While it boots on OnePlus 8, it doesn't boot with stock config on the OnePlus 8 Pro.
Please correct the source codes!!

On Op8 "OpIris" is a few lines in the logs. On op8pro it's this:

Crash logs (not present in op8)
[code]
05-08 18:57:12.570  1633  1633 D OpIrisWhiteListManager: init
05-08 18:57:12.571  1633  1633 D OpIrisWhiteListParser: parseXml sdr2hdr text: com.tencent.qqlive type: 267-3-1 appType :1
05-08 18:57:12.571  1633  1633 D OpIrisWhiteListParser: parseXml sdr2hdr text: com.qiyi.video type: 267-3-1 appType :1
05-08 18:57:12.571  1633  1633 D OpIrisWhiteListParser: parseXml sdr2hdr text: com.youku.phone type: 267-3-1 appType :1
05-08 18:57:12.571  1633  1633 D OpIrisWhiteListParser: parseXml sdr2hdr text: com.oneplus.gallery type: 267-3-1 appType :1
05-08 18:57:12.571  1633  1633 D OpIrisWhiteListParser: parseXml sdr2hdr text: com.tencent.qqsports type: 267-3-1 appType :1
....
05-08 18:57:12.576  1633  1633 E ActivityManager: Caused by: java.util.NoSuchElementException
05-08 18:57:12.576  1633  1633 E ActivityManager:       at android.os.HwBinder.getService(Native Method)
05-08 18:57:12.576  1633  1633 E ActivityManager:       at android.os.HwBinder.getService(HwBinder.java:83)
05-08 18:57:12.576  1633  1633 E ActivityManager:       at sis.sis.zta.zta.zta.sis.getService(Unknown Source:2)
05-08 18:57:12.576  1633  1633 E ActivityManager:       at sis.sis.zta.zta.zta.sis.getService(Unknown Source:2)
05-08 18:57:12.576  1633  1633 E ActivityManager:       at com.oneplus.android.server.iris.ssp.zta(Unknown Source:6)
05-08 18:57:12.576  1633  1633 E ActivityManager:       at com.oneplus.android.server.iris.sis.init(Unknown Source:18)
05-08 18:57:12.576  1633  1633 E ActivityManager:       at com.oneplus.android.server.iris.sis.<init>(Unknown Source:129)
05-08 18:57:12.576  1633  1633 E ActivityManager:       at com.oneplus.android.server.iris.OpIrisService.<init>(Unknown Source:40)
05-08 18:57:12.576  1633  1633 E ActivityManager:       at com.oneplus.android.server.context.OneplusContextStubImpl.<init>(Unknown Source:1699)
[/code]

Then:

[code]
--------- beginning of crash
05-08 18:57:12.583  1633  1633 E AndroidRuntime: *** FATAL EXCEPTION IN SYSTEM PROCESS: main
05-08 18:57:12.583  1633  1633 E AndroidRuntime: java.lang.RuntimeException: Failed to start service com.android.server.am.ActivityManagerService$Life
05-08 18:57:12.583  1633  1633 E AndroidRuntime:        at com.android.server.SystemServiceManager.startService(SystemServiceManager.java:131)
05-08 18:57:12.583  1633  1633 E AndroidRuntime:        at com.android.server.SystemServiceManager.startService(SystemServiceManager.java:116)
05-08 18:57:12.583  1633  1633 E AndroidRuntime:        at com.android.server.am.ActivityManagerService$Lifecycle.startService(ActivityManagerService.
05-08 18:57:12.583  1633  1633 E AndroidRuntime:        at com.android.server.SystemServer.startBootstrapServices(SystemServer.java:688)
05-08 18:57:12.583  1633  1633 E AndroidRuntime:        at com.android.server.SystemServer.run(SystemServer.java:538)
05-08 18:57:12.583  1633  1633 E AndroidRuntime:        at com.android.server.SystemServer.main(SystemServer.java:377)
05-08 18:57:12.583  1633  1633 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
05-08 18:57:12.583  1633  1633 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
05-08 18:57:12.583  1633  1633 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:928)
05-08 18:57:12.583  1633  1633 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'void com.oneplus.andro
05-08 18:57:12.583  1633  1633 E AndroidRuntime:        at com.android.server.am.ActivityManagerService.start(ActivityManagerService.java:2895)
05-08 18:57:12.583  1633  1633 E AndroidRuntime:        at com.android.server.am.ActivityManagerService.access$1000(ActivityManagerService.java:507)
05-08 18:57:12.583  1633  1633 E AndroidRuntime:        at com.android.server.am.ActivityManagerService$Lifecycle.onStart(ActivityManagerService.java:
05-08 18:57:12.583  1633  1633 E AndroidRuntime:        at com.android.server.SystemServiceManager.startService(SystemServiceManager.java:129)
05-08 18:57:12.583  1633  1633 E AndroidRuntime:        ... 8 more
[/code]

This will stop starting of system in the end..

**Comment by tbalden** [comment]
OnePlus didn't publish in this kernel tree : a driver source code that is INSIDE their kernel in the Oneplus8Pro stock boot image.
These you can read in the stock zImage on the phone by default,, so it's not a module missing, but source code unpublished, going against GPL licensing.

Here are the strings missing from the full source tree, so impossible to compile them in at the moment.

OnePlus please publish IRIS sources!

IRIS dsi driver related stuff:

[code]
sde_encoder_disable_autorefresh_handler
sde_encoder_rc_lock
sde_encoder_rc_unlock
***sdr2hdr***
sdr2hdr

qcom,iris-supply-entries
qcom,platform-analog-bypass-gpio
qcom,platform-analog-bypass-status-gpio
qcom,platform-iris-reset-gpio
qcom,platform-iris-vdd-gpio


pxlw,ap-te
pxlw,chip-ver
pxlw,iris-cmd-list
pxlw,iris-cmd-list-1
pxlw,iris-lightup-config
pxlw,iris-lightup-sequence
pxlw,iris-lightup-sequence-cont-splash
pxlw,iris-lightup-sequence-pre0
pxlw,iris-lightup-sequence-pre1
pxlw,iris-me-hres
pxlw,iris-memc-dsc-bpp
pxlw,iris-me-vres
pxlw,iris-mode-switch-sequence
pxlw,iris-mode-switch-sequence-1
pxlw,iris-pq-default-val
pxlw,iris-tx-mode
pxlw,last-for-per-pkt
pxlw,loop-back-mode
pxlw,loop-back-mode-res
pxlw,low-power
pxlw,lut-mode
pxlw,max-color-temp
pxlw,min-color-temp
pxlw,panel-dimming-brightness
pxlw,panel-hbm
pxlw,panel-te
pxlw,panel-type
pxlw,pkt-payload-size
pxlw,pt-last-for-per-pkt

pixelworks
pixelworks
pixelworks-i2c
pixelworks-i2c
pixelworks,iris5
pixelworks,iris5-i2c

[msm-dsi-debug]: offset=%x cnt=%d
MSM_IRIS_OPERATE_CONF
MSM_IRIS_OPERATE_TOOL


iris5_abypass_mode_get
iris5_aod_set
iris5_ccf1.fw
iris5_ccf2.fw
iris5_display_prepare
iris5_fod_post
iris5_fod_set
iris5_func_status
iris5.fw
iris5_gpio_free
iris5_gpio_parse
iris5_gpio_request
iris5_init
iris5_lightoff
iris5_lightup
iris5_loop_back_verify
iris5_operate_conf
iris5_operate_tool
iris5_parse_lut_cmds
iris5_parse_params
iris5_parse_pwr_entries
iris5_power_off
iris5_power_on
iris_abyp_dbg_write
iris_abyp_lp
iris,abyp-panel-command
iris,abyp-panel-command-state
iris_abyp_status_gpio_check
iris_abyp_switch
iris_add_cmd_to_ipidx
IRIS_AL_ENABLE
iris_alloc_buf_for_desc


[DSI]: Iris ESD snow screen error
[DSI]: iris_loop_back_validate finish, ret = %d
[DSI]: iris_panel_ctrl_read_reg failed, rc=%d
[DSI]: iris_panel_ctrl_read_reg id1 failed, rc=%d
[DSI]: iris_panel_ctrl_read_reg id2 failed, rc=%d
[DSI]: not enough memory to hold panel reg dump
[/code]

**Comment by xen0m0rph2020** [comment]
@OnePlusOSSAdmin @aaronqiuchiu

**Comment by xen0m0rph2020** [comment]
@binson-xu

**Comment by binson-xu** [comment]
@xen0m0rph2020   IRIS sources code is in the path of techpack/display/msm/ and arch/arm64/boot/dts/vendor/qcom

**Comment by tbalden** [comment]
Yeah, I found it in the meantime. But it's not straightforward to build
them in.

Can you help out, how to run a build that will correctly include it?

**Comment by xen0m0rph2020** [comment]
> @xen0m0rph2020 IRIS sources code is in the path of techpack/display/msm/ and arch/arm64/boot/dts/vendor/qcom

thanks can you let tbalden know how to include it please?

**Comment by celtare21** [comment]
Meme fest

**Comment by tbalden** [comment]
This might help others to compile for the Op8Pro : https://github.com/tbalden/android_kernel_oneplus_sm8250/commit/6afd66e04ab4c579c0bbc2439c0cd92cf845c13d
