### ISSUE TITLE
qcacld-3.0

### ISSUE THREAD

**Issue by Geofferey** [OnePlusOSS/android_kernel_oneplus_sm8250#19]
Could you please provide the accompanying qcacld-3.0 sources for kernel and their dependencies?

drivers/staging/qcacld-3.0
drivers/staging/qca-wifi-host-cmn
drivers/staging/fw-api

**Comment by YumeMichi** [comment]
Just take them from caf.
https://source.codeaurora.org/quic/la/

**Comment by Geofferey** [comment]
Dude, thank you! I do not know how to navigate that site. :/

My problem was going here.
https://source.codeaurora.org/external/wlan/qcacld-3.0/refs/tags

when I should've been going to the link you have given. Thank you again.

**Comment by YumeMichi** [comment]
> Dude, thank you! I do not know how to navigate that site. :/
> 
> My problem was going here. https://source.codeaurora.org/external/wlan/qcacld-3.0/refs/tags
> 
> when I should've been going to the link you have given. Thank you again.

https://source.codeaurora.org/quic/la/platform/vendor/qcom-opensource/wlan/qcacld-3.0/
https://source.codeaurora.org/quic/la/platform/vendor/qcom-opensource/wlan/qca-wifi-host-cmn/
https://source.codeaurora.org/quic/la/platform/vendor/qcom-opensource/wlan/fw-api/

**Comment by Geofferey** [comment]
@YumeMichi I had already gotten it from your first link but hopefully  this helps others new to CAF attempting to mess with oneplus version of kernel. I knew there was more tags, just not where lol. Have a good one my friend and thank you again. :)
