### ISSUE TITLE
OOS12 sources

### ISSUE THREAD

**Issue by ppajda** [OnePlusOSS/android_kernel_oneplus_sm8250#23]
Can we get OOS12 sources, please?

**Comment by pacman366** [comment]
I have a feeling OnePlus has no plans to release this in a reasonable time frame despite their violation of GPL . You may want to file a file a complaint through gnu.org.

http://www.gnu.org/licenses/gpl-violation.html

**Comment by pacman366** [comment]
This issue will likely need to be re-opened. We're still missing parts of the codebase. see [this](https://github.com/OnePlusOSS/android_vendor_qcom_opensource_audio_kernel_sm8250/issues/1)

**Comment by ppajda** [comment]
Reopening as some sources are missing.
