### ISSUE TITLE
Missing files on OOS12 source?

### ISSUE THREAD

**Issue by DawfukFR** [OnePlusOSS/android_kernel_oneplus_sm8250#26]
https://github.com/OnePlusOSS/android_kernel_oneplus_sm8250/blob/oneplus/sm8250_s_12.1/drivers/ommc
As exemple

**Comment by ppajda** [comment]
Not really
https://github.com/OnePlusOSS/android_vendor_qcom_opensource_audio_kernel_sm8250/tree/oneplus/sm8250_s_12.1/vendor/oplus/kernel_4.19/mmc

**Comment by DawfukFR** [comment]
> Not really https://github.com/OnePlusOSS/android_vendor_qcom_opensource_audio_kernel_sm8250/tree/oneplus/sm8250_s_12.1/vendor/oplus/kernel_4.19/mmc

Thx I haven't see it
