### ISSUE TITLE
Source update

### ISSUE THREAD

**Issue by ppajda** [OnePlusOSS/android_kernel_oneplus_sm8250#27]
Updated OOS12 kernel sources when?
Really, is this that hard to push an update? Cmon.

**Comment by YumeMichi** [comment]
https://github.com/OnePlusOSS/android_kernel_oneplus_sm8250/tree/oneplus/sm8250_s_12.1

**Comment by ppajda** [comment]
Yeah, i know. What i mean is that we are at C.33, but sources are not updated to reflect changes.
