### ISSUE TITLE
'soc/oplus/oplus_wakelock_profiler.h' file not found

### ISSUE THREAD

**Issue by binaryslark** [OnePlusOSS/android_kernel_oneplus_sm8250#35]
```
  CC      kernel/time/alarmtimer.o
../kernel/time/alarmtimer.c:39:10: fatal error: 'soc/oplus/oplus_wakelock_profiler.h' file not found
#include <soc/oplus/oplus_wakelock_profiler.h>
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
```

- the `drivers/soc/oplus/owakelock` module is missing
- `#include <soc/oplus/oplus_wakelock_profiler.h> ` causes the error

Note: i can fix this one with edit line `kernel/time/alarmtimer.c:39:10`(just like what [op8](https://github.com/engstk/op8/blob/5fec68c3d344624954a2780fece6ae7c5b7c6c1e/kernel/time/alarmtimer.c#LL39C50-L39C50) did), but the other `#include <soc/oplus/oplus_wakelock_profiler.h> `  also cause errors

**Comment by OnePlusOSSAdmin** [comment]
```c
#ifdef OPLUS_FEATURE_POWERINFO_STANDBY
#include <soc/oplus/oplus_wakelock_profiler.h>
``` 
It‘s controled by OPLUS_FEATURE_POWERINFO_STANDBY and this is not enabled. 
Enabled feature list is oplus_native_features.mk. Before execute make, please export variables in this file.

**Comment by binaryslark** [comment]
export the `oplus_native_features.mk`(commands below), it works for me. 
```
set -a
. .\oplus_native_features.mk
set +a
```
